### ISSUE TITLE
Horizontal scattering of points within violins

### ISSUE THREAD

**Issue by herrgottsdonner** [bastibe/Violinplot-Matlab#16]
Dear Bastian

Perhaps a very basic question:
Could you clarify the logic according to which the data points are scattered horizontally within each violin?

Sincerely
Johannes

**Comment by bastibe** [comment]
No problem.

They are scattered randomly up to the enclosing kernel density line. This is simply to give a better visual representation of how many points there are. This technique is called "jittering" and is common practice in scatter plots, as otherwise multiple overlapping scatter points could not be distinguished from a single point.

I hope this answers your question?

**Comment by herrgottsdonner** [comment]
Thank you for your fast and competent answer. 
This issue may be closed.

**Comment by herrgottsdonner** [comment]
Thank you for your fast and competent answer.
This issue may be closed.
