### ISSUE TITLE
Fails with "Attempt to reference field of non-structure array"

### ISSUE THREAD

**Issue by ximion** [bastibe/Violinplot-Matlab#4]
Hi!
Thank you for your work on this code! Unfortunately, when trying to use it in Matlab R2015 using the example provided in the README file, it fails with "Attempt to reference field of non-structure array".

Backtrace:
```
obj = 

Attempt to reference field of non-structure array.
Error in Violin/get.ViolinColor (line 222)
            color = obj.ViolinPlot.FaceColor;
Error in Violin (line 138)
            obj.MeanPlot = plot([pos-meanDensity*width pos+meanDensity*width], ...
Error in violinplot (line 81)
            violins(n) = Violin(thisData, n, varargin{:});
```

**Comment by bastibe** [comment]
Can you tell me exactly what code you ran, and what line of your code caused this error? The example in the README works fine on my machine (R2016/R2017).

**Comment by ximion** [comment]
The full retrace:
```
>> load carbig MPG Origin
Origin = cellstr(Origin);
figure
vs = violinplot(MPG, Origin);
ylabel('Fuel Economy in MPG');
xlim([0.5, 7.5]);

obj = 

Attempt to reference field of non-structure array.

Error in Violin/get.ViolinColor (line 222)
            color = obj.ViolinPlot.FaceColor;

Error in Violin (line 138)
            obj.MeanPlot = plot([pos-meanDensity*width pos+meanDensity*width], ...

Error in violinplot (line 81)
            violins(n) = Violin(thisData, n, varargin{:});
 
222             color = obj.ViolinPlot.FaceColor;
```
I wonder whether this is a quirk of R2015...

**Comment by bastibe** [comment]
It seems that way. If I remember correctly, there were some major changes to the way Matlab handles classes in 2014/2015. This might be related to these changes.

It's either that or maybe it's related to the new [Graphic Handles](https://mathworks.com/help/matlab/graphics_transition/major-graphics-changes-in-r2014b.html) in 2014b, where plotting functions like `plot` return objects instead of doubles. You can check that yourself: does `fill` return an object that has a modifyable `FaceColor` property? (Since `obj.ViolinPlot` is a [Patch object](https://mathworks.com/help/matlab/ref/matlab.graphics.primitive.patch-properties.html), as returned by `fill`).

Sorry for not being able to help, but this seems to be an issue with your version of Matlab.

**Comment by ximion** [comment]
`fill` does indeed return a modifiable patch object with a `FaceColor` property. `obj.ViolinPlot` is an empty vector `[]` for some reason though.

Since I do have R2015, this should work and somehow doesn't.

> Sorry for not being able to help, but this seems to be an issue with your version of Matlab.

No worries, since it works for you and the difference is the used Matlab version, it's highly likely that. I would like to know why this fails though, because actually I couldn't find anything obvious between R2015 and R2016 that would impact this function.

**Comment by ximion** [comment]
It actually looks like `MPG` is not a matrix anymore but a long vector instead, and that confuses the violinplot function (it returns in the Violin constructor before actually calling fill)

**Comment by ximion** [comment]
Jup, that's it :-) The only remaining issue is that the `MarkerFaceAlpha` of scatterplots does not exist in R2015a, but was introduced in R2015b....

I really don't think this is worth to put a workaround into this code, instead time is better spent in getting our Matlab version upgraded.
Thanks for your help!
