### ISSUE TITLE
Error for more than seven distributions 

### ISSUE THREAD

**Issue by LucyIris** [bastibe/Violinplot-Matlab#41]
Thank you very much for making this code widely available, it is very useful.

I have just one issue: I'd love to have more than 7 distributions displayed in the same figure, as shown below:

```
vPlot = [out_Program1{1,pat}, out_Program2{1, pat}, out_Program5{1, pat}, out_Program6{1, pat}, out_Program15{1, pat}, out_Program11{1, pat},...
        out_Program12{1, pat}, out_Program13{1, pat}];
    violinplot(vPlot, categorynames, 'Width', 0.3, 'ViolinAlpha', 0.7);
```

When I try this, I get the error:

```
Index in position 1 exceeds array bounds (must not exceed 7).

Error in Violin (line 272)
                    ViolinColor{1} = args.ViolinColor{1}(pos,:);

Error in violinplot (line 179)
        violins(n) = Violin(thisData, n, varargin{:});
```

If you could please suggest how to proceed, I would appreciate very much.

Thank you.

**Comment by mikelgg93** [comment]
Hi! I just checked and I was able to reproduce it. This error is thrown because not enough colours are loaded by default. I will make the changes and do an open request after I solve it. 
Until then, you can pass the 'ViolinColor' parameter, for example, like:

```
vplts= violinplot(vPlot, categorynames, 'Width', 0.3, 'ViolinAlpha', 0.7, 'ViolinColor', {[0 0.4 0.7]});
```
That would plot them all with the same colour and you should not have any problem.
If you will like to change their colour later, you can use the handles:

```
cmap = lines;
for idx= 1: length(vplts)
    vplts(1, idx).ViolinColor = {cmap(idx, :)};
end
```

**Comment by mikelgg93** [comment]
@LucyIris, you can just update the code, https://github.com/bastibe/Violinplot-Matlab/commit/40483a5a8eae7bdd7c1967cb6fde590d8df74bf5 fixes this

**Comment by LucyIris** [comment]
Thank you so much @mikelgg93, this was super fast. And it works!
